# Generated by Django 3.0.6 on 2020-06-09 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='client',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='emp.Client', verbose_name='client task'),
        ),
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='time_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='employee tasked'),
            preserve_default=False,
        ),
    ]
